### ISSUE TITLE
Add song link to now playing command

### ISSUE THREAD

**Issue by JohnMaguire** [JohnMaguire/Cardinal#100]
We list the song name and artist, but a Spotify and/or YouTube link would be awesome.

Or potentially: https://match.audio/

**Comment by JohnMaguire** [comment]
Also gonna say blocked by #110

**Comment by sanjitjain2** [comment]
Hello, I'm interested, I am a very much of a first timer . Is this issue still open?
I would like to help.
Can someone guide me?

**Comment by scheleon** [comment]
Is this issue still open? If so I would like to work on it can someone guide me through the process?

**Comment by paulosgf** [comment]
Hi @JohnMaguire ! this label "blocked" means that PRs are blocked for now?

**Comment by paulosgf** [comment]
I noticed that the documentation is a little confused on configuration part. It mixes usage and configuration. Would you like it if i presented an upgrade?
