### ISSUE TITLE
auth with irc.twitch.tv

### ISSUE THREAD

**Issue by zerocarbthirty** [JohnMaguire/Cardinal#101]
Howdy,

I've been trying to get Cardinal to connect to irc.twitch.tv and it consistently returns this:

cardinal.bot - DEBUG - tmi.twitch.tv sent notice to *: Error logging in

I've verified that I can connect to irc.twitch.tv 6667 with PASS and NICK and it works perfectly fine using the same password. Is there a problem with the password because it has a colon in it? All of the passwords for twitch start with oauth:

if anyone has any idea please let me know.

**Comment by JohnMaguire** [comment]
Hey @zerocarbthirty, thanks for the report. Just to verify, you're using the "password" option in `config.json`, correct? I'll try to reproduce this and figure out what's up.

**Comment by zerocarbthirty** [comment]
i tried both password and server_password

**Comment by JohnMaguire** [comment]
I think I see the issue. Let me verify, then I'll push the fix.

**Comment by JohnMaguire** [comment]
I'm quite certain you're the first person to ever use that option on Cardinal. ;)

The fix has been pushed, feel free to just copy `cardinal/bot.py` if you want. I'll tag a new release too.

**Comment by JohnMaguire** [comment]
Fixed by 5ca0a3c8e8ad0d556286ce5a6befee78d7584998
