### ISSUE TITLE
Support / document Windows usage

### ISSUE THREAD

**Issue by JohnMaguire** [JohnMaguire/Cardinal#113]
Some plugins may not work (dependency issues), and if anything is broken in the core, we want to fix it.

**Comment by TheCryptek** [comment]
I can get to work on it soon if you still need a good run on a windows machine to make sure it all works.

**Comment by JohnMaguire** [comment]
@TheCryptek If you'd like to give it a try on Windows and report back any issues, that'd be awesome! 👍

**Comment by TheCryptek** [comment]
@JohnMaguire Alright just give me a list of commands supported by the bot :P

**Comment by JohnMaguire** [comment]
You can run ".help" to get a list of commands. :)

**Comment by TheCryptek** [comment]
@JohnMaguire Thanks I thought it was @help xD

**Comment by TheCryptek** [comment]
@JohnMaguire After messing with the bot on a windows machine it all seems to working just fine, except for .quit and .dbg_quit the bot doesn't quit for some reason in the terminal it just says

````
2016-12-20 09:59:46,948 - cardinal.bot - DEBUG - TheCryptek!TheCryptek@192.168.43.164 to #Cardinal: .quit
2016-12-20 09:59:46,950 - cardinal.plugins - DEBUG - Attempting to fire event: irc.privmsg
2016-12-20 09:59:46,951 - cardinal.plugins - DEBUG - Calling 0 callbacks for event: irc.privmsg
````

Today I will be bringing it up on a live IRC Network instead of my private local LAN IRC Network and run some tests with authenticating with nickserv.

**Comment by TheCryptek** [comment]
Same issues with .load .unload and .part

**Comment by TheCryptek** [comment]
Also after using .youtube Lynyrd Skynyrd the bot just freezes and doesn't reply to anything including .help

**Comment by JohnMaguire** [comment]
For the admin commands (`.quit`, `.dbg_quit`, `.load`, `.unload`, `.part`, and `.join`) you will need to add your vhost into the `plugins/admin/config.json` file.

Thanks for the YouTube report -- I'll try to check that out soon. 👍

**Comment by TheCryptek** [comment]
I did add my vhost to plugins/admin/config.json as TheCryptek@*

**Comment by JohnMaguire** [comment]
It doesn't understand *. It uses a vhost/hostmask for auth with the idea
that if you identify against nickserv, a hostserv will cloak your hostname.

I like the idea of adding support for a wildcharacter though, thanks!

**Comment by TheCryptek** [comment]
Your welcome, after fixing my vhost I have .quit and stuff working with .youtube I'm running another test with it. Only other issue I have is Cardinal and my other bot fighting but its an alias issue :P

**Comment by TheCryptek** [comment]
Okay, turns out the youtube issue was just a little lag from my network, so all seems to be running good on windows thus far.

**Comment by TheCryptek** [comment]
With the development of plugins do I have to make the .pyc files?

**Comment by JohnMaguire** [comment]
Thanks for testing it out! You didn't experience any issues on your local IRC server?

.pyc files are automatically generated by Python when you run Python code. You don't have to manually create them.

**Comment by TheCryptek** [comment]
No issues at all, but still testing it trying to break it to see what may or may not need fixed
