### ISSUE TITLE
Pulling command definitions from a database

### ISSUE THREAD

**Issue by zerocarbthirty** [JohnMaguire/Cardinal#115]
Hi, I don't really have an issue per se, I am just trying to enhance the functionality of my plugin and I was looking for a little advice. I threw the script below together in about 20 minutes so forgive me if it's not super clean.

```python
import urllib2
import MySQLdb
import logging
from cardinal.decorators import command, help
class zPlugin(object):
        logger = None
        def __init__(self):
                # Initialize logging
                self.logger = logging.getLogger(__name__)
                try:
                        db = MySQLdb.connect(host="localhost", user="throwthis", passwd="awayyyy", db="queue")
                        cur = db.cursor()
                except MySQLdb.Error, e:
                        self.logger.exception("MySQL Error [%d]: %s" % (e.args[0], e.args[1]))
                        return
                try:
                        cur.execute("SELECT trigger FROM commands where status = 0")
                except MySQLdb.Error, e:
                        self.logger.exception("MySQL Error [%d]: %s" % (e.args[0], e.args[1]))
                        return
                czz = list(cur.fetchall())
                db.close()
        @command(['blah', 'blahh', 'blahhh'])
        def zct(self, cardinal, user, channel, msg):
                nick, ident, vhost = user.group(1), user.group(2), user.group(3)
                cmd = msg.split(' ', 1)[0]
                cmd = cmd.replace('!','')
                uh = urllib2.urlopen("http://localhost/whatever.php?user=%s&a=%s" % (nick, cmd))
def setup():
        return zPlugin()
```

The result of that select query should be three rows in which the column trigger is: blah, blahh, and blahhh I am trying to figure out how to just replace the @command definition with info from the database. I am terrible with python too, this is my first time using it.

thanks in advance.

**Comment by JohnMaguire** [comment]
Hey @zerocarbthirty. The decorators (`@command` and `@help`, e.g.) are actually pretty new. The old way of assigning commands worked a lot like the `.regex` I showed you in #114. I think if, in `__init__`, you do something like this: `self.zct.commands = ['trigger1', 'trigger2']`, Cardinal should register these triggers.

The `@command` decorator actually just sets this property for you: https://github.com/JohnMaguire/Cardinal/blob/master/cardinal/decorators.py#L16

In fact, I believe that updating this property should allow you to update the list of triggers without reloading the plugin, or restarting Cardinal at all. If this does not work, try `zPlugin.zct.commands = ['trigger1', 'trigger2']` instead, but I'm pretty sure a reference to `self.` will work.

I'd also love if you could report back and let me know how this worked!

**Comment by zerocarbthirty** [comment]
okay so you are saying that I will need to find a way to create a list from the result of that query and then assign that list to self.zct.commands?

**Comment by JohnMaguire** [comment]
Yup. Get your triggers into a representation like this: `['trigger1', 'trigger2', 'trigger3']`, and assign it to `self.zct.commands`, and the bot should call the command on those triggers. Please do let me know that it worked, as I've never attempted this before. :)

**Comment by zerocarbthirty** [comment]
Okay I will try and see if I can figure out how to do that in python, in PHP it would take me 0 seconds. we're both in a world of firsts, the next thing i have to figure out how to do is track how long people spend in my channel hahahaha

**Comment by JohnMaguire** [comment]
:+1: Cardinal is how I learned to start writing Python from a PHP background actually. :)

As far as tracking users joining and leaving your channels go, this page will probably be helpful: https://github.com/JohnMaguire/Cardinal/wiki/Events
