### ISSUE TITLE
"Can't call an event that does not exist: urls.detection" after reloading URLs plugin

### ISSUE THREAD

**Issue by Shares5** [JohnMaguire/Cardinal#119]
The URLs addon works fine up until i do ".reload urls" at which point it spits out that error at me into the console when a link is posted. here is the full errorlog: https://gist.githubusercontent.com/Shares5/5037d6dcdfe919b1e17db30706994e20/raw/3f81befbb7d7ab64f565a9e346718c45a2a4596b/error%2520log

Any help would be appreciated

**Comment by JohnMaguire** [comment]
@Shares5 What version of Cardinal are you using? I'll try to take a look soon, sorry for the delay. This slipped through my radar.

**Comment by Shares5** [comment]
Thanks, I was using this fork https://github.com/CrushAndRun/Cardinal-Automata

**Comment by JohnMaguire** [comment]
@Shares5 The fork is missing these commits: 8ce0e19831f2ae87663c6f445db9ef3cc71234f7, f2d45d8d3a950a4e9747e87424c3ec44ac643014

They resolved the issue. (Sorry this is three years late, lol...)

**Comment by JohnMaguire** [comment]
I may have misunderstood, and this was actually this bug: https://github.com/JohnMaguire/Cardinal/commit/e7cdc9fdb5b564b29641f4eb707ea6d27940fabf
