### ISSUE TITLE
Provide some HOWTO on usage of Cardinal bot

### ISSUE THREAD

**Issue by Humoyun** [JohnMaguire/Cardinal#124]
I am having problem with how to use Cardinal. After running ./cardinal.py I am getting: 

`2016-12-22 05:06:17,772 - cardinal.plugins - DEBUG - Attempting to fire event: irc.raw
2016-12-22 05:06:17,772 - cardinal.plugins - DEBUG - Calling 0 callbacks for event: irc.raw
`
message on about every minute, when I issue some command the terminal is showing nothing 
e.g. `/msg #celery he everybody`

**Comment by boretom** [comment]
Hey Humoyun,
I was having the same problem after trying to use Cardinal (again).

In the channel I let the bot run I '.help'. That shows you what commands are available. Then use that command the same way: .<command>, e.g.:

[#whatever-channel] .ud cardinal
UD for cardinal: a "prince" of the Catholic Church; cardinals elect the pope.  They are usually bishops. They wear scarlet dresses. (http://cardinal.urbanup.com/2045110)

Hope that helps

**Comment by JohnMaguire** [comment]
Hey, thanks for the feedback that I should provide some better instructions.

As @boretom said, it's expected that you interact with Cardinal through a channel on the IRC network, or through a private message -- there is no command-line interface once the bot has been launched.

Hope that helps!

**Comment by Humoyun** [comment]
@JohnMaguire, So as I understand I should start Cardinal on the background and then I should connect IRC net by IRC client like WeChat, after joining some #channel e.g., #celery on freenode, I can interact with cardinal through this channel (querying, make use of cardinal's plugins, wikipedia, calculator, github...) and Cardinal Bot will send me back the desired info. I think I misunderstand the Cardinal in the first place, at the very beginning you write "Cardinal is IRC bot not a IRC client" :)

**Comment by Humoyun** [comment]
@JohnMaguire and one more question, Can I add geocoding/reverse-geocoding plugins to Cardinal? Do you think it is a good idea? Actually I am very interested in Open Source Projects but zero experience in Open Source Community, so I looked for some active ones so that I can contribute. And this is my first step towards Open Source hence if possible can you please give some guidelines or suggestions. :) thanks in advance!!!

**Comment by JohnMaguire** [comment]
@Humoyun Correct, it is an IRC bot not an IRC client. :)

> Another IRC bot, you say? Just what the world needed!

Hopefully this tongue-in-cheek comment at the top of the README is sufficient? I still think it's good feedback that I should add some more info on how to first interact with the bot.

I'm not totally sure what your plugin would do, but I'm pretty liberal about accepting pull requests and plugins! Eventually, I'd like to add a package manager (#79) so that the plugins don't need to be contained in this core.
