### ISSUE TITLE
Plugins are not sending to IRC client instead the results are being displayed just on the terminal where I started cardinal bot

### ISSUE THREAD

**Issue by Humoyun** [JohnMaguire/Cardinal#125]
Could you please provide some HOW-TO on plugin usage, because when I use commands they are not returning to IRC client but it is showing results in Cardinal bot itself, for example, I issued: /msg my_cardinal_bot .google <"python">, it is returning results but not to my IRC client instead it is just showing the results on terminal where I started cardinal bot.

**Comment by JohnMaguire** [comment]
@Humoyun Sorry, I missed this issue. What IRC server were you connected to?

**Comment by absolution** [comment]
I tried to replicate this issue but was unable to. When using the command provided by @Humoyun I received a PM from the bot saying:
Cardinal: Couldn't find any results for your query

**Comment by absolution** [comment]
This seems more of an issue related to #124

**Comment by JohnMaguire** [comment]
@absolution I'm not sure... this was posted 6 days after the last comment on #124. I'm thinking that the bot may have been in a channel with [`+M`](https://wiki.swiftirc.net/wiki/Channel_modes#.2BM_2) or similar set. Otherwise, it may be an incompatibility with some server software.
