### ISSUE TITLE
Can't use time.sleep() inside loops

### ISSUE THREAD

**Issue by target111** [JohnMaguire/Cardinal#135]
I'm trying to write a module that will allow the user to spam the channel with a message for a number of times so I'm using a loop to send the same message again and again. My problem is that if I add a delay to prevent the bot from recvq, it will print the messages in the terminal with delay and once thats done it sends them all to the channel at the same time instead of sending one message at a time each time it loops. Is there a way I could fix this? 

Here's my plugin: https://bpaste.net/show/ca10b573d6f4

**Comment by JohnMaguire** [comment]
To make sure I'm understanding:

```
        for _ in range(times):
            fg = self.color()
            bg = self.color()

            while bg == fg: bg = self.color()

            cardinal.sendMsg(channel, "\x02\x03" + fg + "," + bg + spam_message.upper() + "\x03\x02")
            time.sleep(1)
```

You're saying that this prints a message to the terminal once every second, but does not send them all until the function returns? That's not the behavior I would expect, so I want to confirm.

**Comment by JohnMaguire** [comment]
Also, unrelated, you may be able to get a good approximate "safe" line length by using `twisted.words.protocol.irc.IRCClient._safeMaximumLineLength`.

**Comment by target111** [comment]
Thanks for responding this fast! Yes the bot only sends the messages after the function returns with no delay, instead I can see them printed in the terminal with the delay.

**Comment by JohnMaguire** [comment]
That's odd. I wonder if perhaps the server has sent a PING, and is waiting on the bot to send a PONG before accepting the messages the bot is sending? Can you get debug logs from the bot when this occurs?

**Comment by JohnMaguire** [comment]
I think I covered getting debug logs a bit here: https://github.com/JohnMaguire/Cardinal/wiki/Configuring-logging

**Comment by JohnMaguire** [comment]
One issue you may run into here (though I'm not seeing how it would cause this issue... perhaps if the server sent a PING and is waiting on a PONG before handling the PRIVMSGs we are sending) is that plugins are currently totally synchronous in Cardinal. So while the method here is being executed, Cardinal can't respond to server actions. This means that for up to 100 seconds after a `=spam` call, the bot won't be able to do anything else, and will likely be booted from the network due to failing to respond to PINGs. You should consider using the Twisted Reactor to call the spam for you: https://twistedmatrix.com/documents/16.5.0/core/howto/defer.html

You would probably write something like:

```
from twisted import reactor
# ...
def _sendSpam(cardinal, times, channel, message):
    cardinal.sendMsg(channel, message)
    reactor.callLater(1, _sendSpam, cardinal, times - 1, channel, message)
```

Then instead of your loop, you'd just call that function. Didn't test this, but should be pretty close to working. This is a similar approach to how the `remind` plugin works.

**Comment by target111** [comment]
Unfortunately I won't be able to provide the debug logs until tomorrow but I'm pretty sure this is not a ping issue since I tried running it a few times before opening this.
Thanks for the tip on twisted.words.protocol.irc.IRCClient._safeMaximumLineLength though :)

I also joined the official dark science channel so it might be easier to discuss this there..

**Comment by JohnMaguire** [comment]
I'm actually rarely on IRC anymore, ironically. I'm in EST timezone, so wouldn't be on IRC except after work hours. May try and jump on to discuss. Would love to get some DEBUG logs though, would be cool to see what's happening under the covers.

**Comment by target111** [comment]
Going to bed now so I'm gonna be off irc. I'll post the logs tomorrow though. Thanks for your help!

**Comment by target111** [comment]
Here's the debug log: https://bpaste.net/show/605a81ae1e35

**Comment by target111** [comment]
I was able to get it working using your reactor solution but this does not actually solve the problem...

**Comment by JohnMaguire** [comment]
I believe [this relates directly to this problem](http://twistedmatrix.com/trac/wiki/FrequentlyAskedQuestions#WhydoesittakealongtimefordataIsendwithtransport.writetoarriveattheothersideoftheconnection).

Twisted is a framework meant for writing asynchronous code without threads. This works by allowing Twisted's Reactor to schedule calls to functions. Cardinal generally gives up control to the Reactor whenever an action is not being performed. This allows the Reactor to sit and read data on the connection, and call the correct functions when data is received.

It appears that in this same manner, Twisted is not actually writing data to the connection when `transport.write()` is called (as this is a blocking operation). This means that until control is given up to the Reactor, the data won't be sent.

There are a few ways of trying to fix this. At one point, I was pursuing multi-process plugins, such that plugins would not block operations, and removing Twisted. It may make more sense to simply implement Twisted more fully to take advantage of async operations. Unfortunately, this probably won't be done soon. In the meantime, you should use `reactor.callLater` to handle operations that do not need to be handled immediately, to prevent blocking the Reactor with a long-running loop like this.

**Comment by target111** [comment]
Thanks for explaining why this problem occurs. I'll keep using `reactor.callLater` until a future version that fixes this is released. I have one more question unrelated to this issue though and if you could answer it that'd be great. :)
Is it possible to implement a game like hangman in a plugin without blocking other functions? (example: https://github.com/target111/Cloudy/blob/master/Cloudy/main.py#L537)
