### ISSUE TITLE
Add music indicator to YouTube videos? Maybe color?

### ISSUE THREAD

**Issue by JohnMaguire** [JohnMaguire/Cardinal#179]
I have to guess, given YT Music, and the fact that YouTube has categories, we can determine whether the video is actually a song. If it is, maybe we could use the headphone emoji, or a music (♫ / ♪) symbol to show it as such in the channel?

**Comment by rijandev** [comment]
John I’d like to contribute to this project. I am new to Open source contribute. How do you suggest I go about adding the music signs?

**Comment by JohnMaguire** [comment]
Hi @rijandev -

The first step would be checking the [Youtube Data API](https://developers.google.com/youtube/v3/docs) to find a way to detect if the video belongs to a music category.

The next step would be to check for this data in the plugin itself, and add some sort of symbol in the event that you detect that category: https://github.com/JohnMaguire/Cardinal/blob/master/plugins/youtube/plugin.py

Finally, test the functionality manually by connecting the bot to an IRC network and trying `.yt <some song name>` as well as pasting a URL to a music video, and verifying that it correctly adds the music symbols. You shouldn't need to request an API key, as a Youtube API key is included in this repository (since Youtube doesn't rate limit or anything.)

**Comment by aaitbr** [comment]
Hey @JohnMaguire 
I'm new to the world of contribution. Can i start by working on this one ? if it's not done yet !

**Comment by JohnMaguire** [comment]
@aaitbr Please go ahead! This API might provide a list of categories, which we can check to see if there's any way to find music-related ones: https://developers.google.com/youtube/v3/docs/videoCategories/list

**Comment by aaitbr** [comment]
@JohnMaguire Thank u ! i'll see that 
& I'll let you know if anything is unclear ! if you don't mind

**Comment by MelstromH** [comment]
Hi, is this issue still open? It seems that several other people have made attempts.

**Comment by JohnMaguire** [comment]
Thanks, you're correct, this issue was resolved.
