### ISSUE TITLE
Create a Github plugin

### ISSUE THREAD

**Issue by JohnMaguire** [JohnMaguire/Cardinal#72]
Features:

- [ ] Notify of new commits / issues / pull requests
- [ ] Ability to quickly link to issues (e.g. ".issue 12" or ".issue web UI")

**Comment by S0lll0s** [comment]
How do I write an plugin that has it's own event loop / listens for github updates?

**Comment by S0lll0s** [comment]
This issue will automatically be closed if you merge #78

**Comment by JohnMaguire** [comment]
Regarding listening for Github updates, my plan is to create a "web" plugin (#58) that would allow Github to call a webhook on it. I wanted to avoid forking / threading each plugin in Cardinal (i.e. allowing them to run an event loop.)

I'm not sure this is the most valid approach, but I have ideas on the web plugin being extensible in other ways as well (i.e. #71)

**Comment by JohnMaguire** [comment]
This is awesome! Just made a couple tweaks for consistency. Thank you very much.
