### ISSUE TITLE
On Wikipedia disambiguation pages, we should give some of the top options

### ISSUE THREAD

**Issue by JohnMaguire** [JohnMaguire/Cardinal#97]
(In the `wikipedia` plugin!)

**Comment by JohnMaguire** [comment]
It may also be prudent to use this: https://pypi.python.org/pypi/wikipedia

**Comment by scarescrow** [comment]
When you say some of the top options, what exactly do you mean?

**Comment by JohnMaguire** [comment]
![screen shot 2017-02-15 at 11 33 51 am](https://cloud.githubusercontent.com/assets/440033/22984221/ad0b04fe-f372-11e6-8c4c-eacab8644cb6.png)

Great question! I'm not sure which of these make more sense to include. Maybe just a random selection?

**Comment by scarescrow** [comment]
Okay, I would love to contribute. But while I have a fair amount of experience in python, I'm new to contributing to open source. I'll give this a shot.

**Comment by scarescrow** [comment]
I've created a pull request. https://github.com/JohnMaguire/Cardinal/pull/126

**Comment by JohnMaguire** [comment]
Instead we just mark these pages as "Dismabiguation" now per the fix for #185.
